#                    ##
#                 ## ##        .
#              ## ## ##       ==
#           ## ## ## ##      ===
#       /""""""""""""""""\___/ ===
#  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
#       \______ o          __/
#         \    \        __/
#          \____\______/
#
#          |          |
#       __ |  __   __ | _  __   _
#      /  \| /  \ /   |/  / _\ |
#      \__/| \__/ \__ |\_ \__  |
#

version: "3"

networks:
  doscom:
    external:
      name: ${NETWORK_DOCKER}

services:
  #doscom.org Applications
  doscom_apps:
    restart: always
    build:
      context: ./
      dockerfile: doscom_apps.dockerfile
    container_name: doscom_apps
    volumes:
      - ${VOLUME_DOSCOM}:/usr/local/apache2/htdocs
    networks:
      - doscom
    healthcheck:
      #test: curl --fail http://localhost/ || exit 1
      test: curl -f -s -o /dev/null -w "%{http_code}\n" http://localhost/ || exit1
      interval: ${HEALTH_INTERVAL}
      timeout: ${HEALTH_TIMEOUT}
      retries: ${HEALTH_RETRIES}
      #start_period: ${HEALTH_PERIOD}
    
  #pinguin.dinus.ac.id Applications
  pinguin_apps:
    restart: always
    build:
      context: ./
      dockerfile: pinguin_apps.dockerfile
    container_name: pinguin_apps
    volumes:
      - ${VOLUME_PINGUIN}:/usr/local/apache2/htdocs
      - ${VOLUME_ISO}:/home/DATA/iso
    networks:
      - doscom
    healthcheck:
      #test: curl --fail http://localhost/ || exit 1
      test: curl -f -s -o /dev/null -w "%{http_code}\n" http://localhost/ || exit1
      interval: ${HEALTH_INTERVAL}
      timeout: ${HEALTH_TIMEOUT}
      retries: ${HEALTH_RETRIES}
      #start_period: ${HEALTH_PERIOD}

  #Portainer dashboard Applications
  dashboard_apps:
    restart: always
    privileged: true
    image: portainer/portainer
    container_name: dashboard_apps
    volumes:
      - ${VOLUME_DASHBOARD}:/data portainer/portainer
      - ${DOCKER_SOCKET}:/var/run/docker.sock
    networks:
      - doscom

  #Load Balancer
  pinguin_lb:
    restart: always
    build:
      context: ./
      dockerfile: pinguin_lb.dockerfile
    container_name: pinguin_lb
    volumes:
      #- ${VOLUME_LB}:/var/www/html
      - ${CONF_LB}:/etc/nginx/conf.d/default.conf
    links:
      - doscom_apps:doscom_apps
      - pinguin_apps:pinguin_apps
      - dashboard_apps:dashboard_apps
    external_links:
      - mariadb_pinguin:mariadb_pinguin
      - mongodb_pinguin:mongodb_pinguin
    #depends_on:
      #- SERVICE
    networks:
      - doscom
    ports:
      - 80:80
    healthcheck:
      #test: curl --fail http://localhost/ || exit 1
      test: curl -f -s -o /dev/null -w "%{http_code}\n" http://localhost/ || exit1
      interval: ${HEALTH_INTERVAL}
      timeout: ${HEALTH_TIMEOUT}
      retries: ${HEALTH_RETRIES}
      #start_period: ${HEALTH_PERIOD}
